# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Docker.Cagent
PackageVersion: v1.9.2
InstallerType: portable
Commands:
- cagent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/cagent/releases/download/v1.9.2/cagent-windows-amd64.exe
  InstallerSha256: 1F7071C7643183542609E155BE505F870334AC70AB02DA755C716F924CA7CECD
- Architecture: arm64
  InstallerUrl: https://github.com/docker/cagent/releases/download/v1.9.2/cagent-windows-arm64.exe
  InstallerSha256: 15FD2AF46FB64C69535325888A09CDC9AE98202DA8F578CA215BFC10C81742D1
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2025-10-30
